# Lecture 6 — Worked Examples

This notebook contains the **worked code examples only**. The item numbers are exactly the same as on the tutorial website. Examples and exercises share one numbering sequence inside each tutorial, so gaps in this notebook are intentional: those missing numbers belong to exercises in the separate Exercises notebook.

**Numbering rule:** never renumber examples inside this notebook. Use the website identifier unchanged.

## Safe, repeatable use — the course files stay unchanged

This notebook reads course CSV files from GitHub through **read-only web addresses**. Running a cell downloads a fresh snapshot into the temporary Colab session; it cannot edit or overwrite the file in the course repository.

- Transformations are performed on a separate in-memory working copy.
- The notebook does not mount Google Drive, call the GitHub API, commit, or push.
- Any exported files are student output copies stored in a separate `tutorial_outputs` folder in the current runtime.
- Re-running the notebook starts from the same repository source. In Colab, **Runtime → Restart session and run all** gives a completely fresh demonstration.

You can therefore teach from these notebooks repeatedly without changing the canonical course data.

# Tutorial 3.15 — From inspection to cleaning

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.15.1 — A simple example

**Website locator:** Example 3.15.1

In [1]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

labels = ["Housing", "housing", "Housing ", "HOUSING"]

print(labels[0] == labels[1])
print(labels[0] == labels[2])
print(labels[0] == labels[3])

False
False
False

## Example 3.15.2 — A simple example (continued)

**Website locator:** Example 3.15.2

In [3]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

# Re-create the small teaching input so this example can run by itself.
labels = ["Housing", "housing", "Housing ", "HOUSING"]
cleaned_labels = []

for label in labels:
    cleaned_label = label.strip().lower()
    cleaned_labels.append(cleaned_label)

print(cleaned_labels)

['housing', 'housing', 'housing', 'housing']

# Tutorial 3.16 — Protect the raw data and create a working copy

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.16.1 — Step 1: import pandas

**Website locator:** Example 3.16.1

In [ ]:
import pandas as pd

## Example 3.16.2 — Step 2: load the raw CSV

**Website locator:** Example 3.16.2

In [5]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)

## Example 3.16.3 — Step 3: inspect the shape

**Website locator:** Example 3.16.3

In [6]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df_raw.shape)

(121, 14)

## Example 3.16.4 — Step 4: create a working copy

**Website locator:** Example 3.16.4

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df = df_raw.copy()

## Example 3.16.5 — Step 5: verify that both currently match

**Website locator:** Example 3.16.5

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df_raw.shape)
print(df.shape)

## Example 3.16.6 — Why `.copy()` matters

**Website locator:** Example 3.16.6

In [8]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df = df_raw

## Example 3.16.7 — Why `.copy()` matters (continued)

**Website locator:** Example 3.16.7

In [9]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df = df_raw.copy()

## Example 3.16.8 — Optional safety check

**Website locator:** Example 3.16.8

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

assert df_raw.shape == (121, 14)

# Tutorial 3.17 — Build a data-quality audit

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.17.1 — Start with the familiar inspection commands

**Website locator:** Example 3.17.1

In [17]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df.shape)
print(df.columns)
print(df.dtypes)
df.info()

(121, 14)
Index(['record_id', 'report_month', 'city', 'service_type', 'cases_received',
       'cases_resolved', 'resolution_days', 'satisfaction_score',
       'digital_cases', 'in_person_cases', 'repeat_contacts',
       'complaints_received', 'staff_hours', 'feedback'],
      dtype='object')
record_id               object
report_month            object
city                    object
service_type            object
cases_received           int64
cases_resolved           int64
resolution_days         object
satisfaction_score     float64
digital_cases            int64
in_person_cases          int64
repeat_contacts          int64
complaints_received      int64
staff_hours            float64
feedback                object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   record_id            121 non-null    object
 1   report_month         121 non-null    object
 2   city                 121 non-null    object
 3   service_type         121 non-null    object
 4   cases_received       121 non-null    int64
 5   cases_resolved       121 non-null    int64
 6   resolution_days      121 non-null    object
 7   satisfaction_score   117 non-null    float64
 8   digital_cases        121 non-null    int64
 9   in_person_cases      121 non-null    int64
 10  repeat_contacts      121 non-null    int64
 11  complaints_received  121 non-null    int64
 12  staff_hours          121 non-null    float64
 13  feedback             118 non-null    object
dtypes: float64(2), int64(6), object(6)
memory usage: 13.4+ KB

## Example 3.17.2 — Start with the familiar inspection commands (continued)

**Website locator:** Example 3.17.2

In [13]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df.head()

,record_id,report_month,city,service_type,cases_received,cases_resolved,resolution_days,satisfaction_score,digital_cases,in_person_cases,repeat_contacts,complaints_received,staff_hours,feedback
0,SR2026-0001,2026-01-01,Copenhagen,Housing,130,116,8.0,3.5,88,42,17,10,87.8,"The guidance was clear, but the supporting-doc..."
1,SR2026-0002,2026-01-01,Copenhagen,Transport,124,110,5.1,3.9,92,32,10,8,54.7,Several users asked for clearer information ab...
2,SR2026-0003,2026-01-01,Copenhagen,Employment,105,93,5.5,3.9,73,32,14,5,58.2,Useful advice and a friendly response from staff.
3,SR2026-0004,2026-01-01,Copenhagen,Waste,104,94,4.9,4.2,80,24,6,4,34.3,"Helpful guidance, but some users reported dela..."
4,SR2026-0005,2026-01-01,Copenhagen,Citizen Services,166,152,3.1,4.3,137,29,9,6,48.9,The response was fast and the information was ...

## Example 3.17.3 — Start with the familiar inspection commands (continued)

**Website locator:** Example 3.17.3

In [14]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   record_id            121 non-null    object
 1   report_month         121 non-null    object
 2   city                 121 non-null    object
 3   service_type         121 non-null    object
 4   cases_received       121 non-null    int64
 5   cases_resolved       121 non-null    int64
 6   resolution_days      121 non-null    object
 7   satisfaction_score   117 non-null    float64
 8   digital_cases        121 non-null    int64
 9   in_person_cases      121 non-null    int64
 10  repeat_contacts      121 non-null    int64
 11  complaints_received  121 non-null    int64
 12  staff_hours          121 non-null    float64
 13  feedback             118 non-null    object
dtypes: float64(2), int64(6), object(6)
memory usage: 13.4+ KB

## Example 3.17.4 — Count missing values by column

**Website locator:** Example 3.17.4

In [18]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

missing_counts = df.isna().sum()
print(missing_counts)

record_id              0
report_month           0
city                   0
service_type           0
cases_received         0
cases_resolved         0
resolution_days        0
satisfaction_score     4
digital_cases          0
in_person_cases        0
repeat_contacts        0
complaints_received    0
staff_hours            0
feedback               3
dtype: int64

## Example 3.17.5 — Count missing values by column (continued)

**Website locator:** Example 3.17.5

In [19]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

missing_counts = df.isna().sum()
print(missing_counts[missing_counts > 0])

satisfaction_score    4
feedback              3
dtype: int64

## Example 3.17.6 — Calculate missing percentages

**Website locator:** Example 3.17.6

In [20]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

missing_percent = df.isna().mean() * 100
print(missing_percent[missing_percent > 0].round(1))

satisfaction_score    3.3
feedback              2.5
dtype: float64

## Example 3.17.7 — Count exact duplicate rows

**Website locator:** Example 3.17.7

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

exact_duplicate_count = df.duplicated().sum()
print("Exact duplicate rows:", exact_duplicate_count)

## Example 3.17.8 — Count repeated identifiers

**Website locator:** Example 3.17.8

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

repeated_id_mask = df["record_id"].duplicated(keep=False)
repeated_ids = df.loc[repeated_id_mask, "record_id"]

print(repeated_ids)

## Example 3.17.9 — Inspect category spellings

**Website locator:** Example 3.17.9

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df["city"].value_counts(dropna=False))
print(df["service_type"].value_counts(dropna=False))

## Example 3.17.10 — Inspect numeric summaries

**Website locator:** Example 3.17.10

In [21]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

numeric_columns = [
    "cases_received",
    "cases_resolved",
    "resolution_days",
    "satisfaction_score",
    "digital_cases",
    "in_person_cases",
    "repeat_contacts",
    "complaints_received",
    "staff_hours"
]

print(df[numeric_columns].describe())

       cases_received  cases_resolved  satisfaction_score  digital_cases  \
count      121.000000      121.000000          117.000000     121.000000
mean       104.570248       98.826446            4.112821      75.826446
std         27.256750       26.195953            0.526953      25.495973
min         -4.000000        0.000000            0.000000       0.000000
25%         86.000000       82.000000            3.900000      57.000000
50%        102.000000       95.000000            4.200000      74.000000
75%        122.000000      113.000000            4.300000      91.000000
max        185.000000      176.000000            6.200000     154.000000

       in_person_cases  repeat_contacts  complaints_received  staff_hours
count       121.000000       121.000000           121.000000   121.000000
mean         28.925620         9.462810             4.950413    46.743802
std           7.417508         9.832803             2.472688    18.199899
min           0.000000         0.000000            -2.000000     0.000000
25%          24.000000         6.000000             3.000000    33.500000
50%          28.000000         8.000000             4.000000    41.000000
75%          32.000000        11.000000             7.000000    55.700000
max          48.000000       107.000000            13.000000   101.300000

## Example 3.17.11 — Create a reusable audit table

**Website locator:** Example 3.17.11

In [22]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

audit = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "missing_n": df.isna().sum(),
    "missing_pct": (df.isna().mean() * 100).round(1),
    "unique_n": df.nunique(dropna=True)
})

print(audit)

                       dtype  missing_n  missing_pct  unique_n
record_id             object          0          0.0       119
report_month          object          0          0.0         7
city                  object          0          0.0         9
service_type          object          0          0.0         9
cases_received         int64          0          0.0        71
cases_resolved         int64          0          0.0        64
resolution_days       object          0          0.0        55
satisfaction_score   float64          4          3.3        16
digital_cases          int64          0          0.0        60
in_person_cases        int64          0          0.0        30
repeat_contacts        int64          0          0.0        20
complaints_received    int64          0          0.0        13
staff_hours          float64          0          0.0       105
feedback              object          3          2.5        27

# Tutorial 3.18 — Missing values: find first, decide second

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.18.1 — Find rows with missing feedback

**Website locator:** Example 3.18.1

In [23]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

missing_feedback = df[df["feedback"].isna()]
missing_feedback.head()

,record_id,report_month,city,service_type,cases_received,cases_resolved,resolution_days,satisfaction_score,digital_cases,in_person_cases,repeat_contacts,complaints_received,staff_hours,feedback
17,SR2026-0018,2026-01-01,Aalborg,Employment,70,62,5.4,4.1,42,28,8,3,40.7,NaN
75,SR2026-0076,2026-04-01,Aalborg,Housing,96,88,5.6,3.7,58,38,12,7,67.5,NaN
117,SR2026-0118,2026-06-01,Aalborg,Employment,66,65,4.2,4.2,42,24,6,3,37.5,NaN

## Example 3.18.2 — Find rows missing any value

**Website locator:** Example 3.18.2

In [24]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

rows_with_any_missing = df[df.isna().any(axis=1)]
print(rows_with_any_missing.shape)

(7, 14)

## Example 3.18.3 — Do not automatically drop missing rows

**Website locator:** Example 3.18.3

In [25]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df.dropna()

,record_id,report_month,city,service_type,cases_received,cases_resolved,resolution_days,satisfaction_score,digital_cases,in_person_cases,repeat_contacts,complaints_received,staff_hours,feedback
0,SR2026-0001,2026-01-01,Copenhagen,Housing,130,116,8.0,3.5,88,42,17,10,87.8,"The guidance was clear, but the supporting-doc..."
1,SR2026-0002,2026-01-01,Copenhagen,Transport,124,110,5.1,3.9,92,32,10,8,54.7,Several users asked for clearer information ab...
2,SR2026-0003,2026-01-01,Copenhagen,Employment,105,93,5.5,3.9,73,32,14,5,58.2,Useful advice and a friendly response from staff.
3,SR2026-0004,2026-01-01,Copenhagen,Waste,104,94,4.9,4.2,80,24,6,4,34.3,"Helpful guidance, but some users reported dela..."
4,SR2026-0005,2026-01-01,Copenhagen,Citizen Services,166,152,3.1,4.3,137,29,9,6,48.9,The response was fast and the information was ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,SR2026-0116,2026-06-01,Aalborg,Housing,89,85,5.9,3.9,53,36,13,8,56.8,Staff were friendly and the final answer was h...
116,SR2026-0117,2026-06-01,Aalborg,Transport,80,79,3.4,4.2,56,24,6,4,32.4,"The digital form worked well, although some in..."
118,SR2026-0119,2026-06-01,Aalborg,Waste,71,70,2.3,4.3,49,22,4,4,23.3,Collection information was easy to understand ...
119,SR2026-0120,2026-06-01,Aalborg,Citizen Services,94,93,1.8,4.7,67,27,4,3,29.8,The response was fast and the information was ...
120,SR2026-0027,2026-02-01,Aarhus,Transport,110,102,4.9,4.2,79,31,6,7,42.5,"The digital form worked well, although some in..."

## Example 3.18.4 — Do not automatically drop missing rows (continued)

**Website locator:** Example 3.18.4

In [26]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

rows_before = len(df)
rows_after_drop_all = len(df.dropna())
rows_removed = rows_before - rows_after_drop_all

print("Rows before:", rows_before)
print("Rows after dropna():", rows_after_drop_all)
print("Rows that would be removed:", rows_removed)

Rows before: 121
Rows after dropna(): 114
Rows that would be removed: 7

## Example 3.18.5 — Dropping rows only for a specific requirement

**Website locator:** Example 3.18.5

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

satisfaction_subset = df.dropna(subset=["satisfaction_score"]).copy()

## Example 3.18.6 — Filling missing values

**Website locator:** Example 3.18.6

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["satisfaction_score"] = df["satisfaction_score"].fillna(df["satisfaction_score"].mean())

## Example 3.18.7 — Missing text

**Website locator:** Example 3.18.7

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

def tokenize_feedback_safely(text):
    if pd.isna(text):
        return []

    return str(text).split()


print(tokenize_feedback_safely(None))

# Tutorial 3.19 — Duplicates and repeated identifiers

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.19.1 — Find exact duplicates

**Website locator:** Example 3.19.1

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

exact_duplicate_mask = df.duplicated(keep=False)
exact_duplicates = df[exact_duplicate_mask]

exact_duplicates

## Example 3.19.2 — Remove a confirmed exact duplicate

**Website locator:** Example 3.19.2

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

rows_before = len(df)

df = df.drop_duplicates().copy()

rows_after = len(df)
print("Rows removed:", rows_before - rows_after)

## Example 3.19.3 — Find repeated `record_id` values

**Website locator:** Example 3.19.3

In [27]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

repeated_id_mask = df["record_id"].duplicated(keep=False)
repeated_id_rows = df[repeated_id_mask].sort_values("record_id")

repeated_id_rows

,record_id,report_month,city,service_type,cases_received,cases_resolved,resolution_days,satisfaction_score,digital_cases,in_person_cases,repeat_contacts,complaints_received,staff_hours,feedback
26,SR2026-0027,2026-02-01,Aarhus,Transport,110,102,4.9,4.2,79,31,6,7,42.5,"The digital form worked well, although some in..."
120,SR2026-0027,2026-02-01,Aarhus,Transport,110,102,4.9,4.2,79,31,6,7,42.5,"The digital form worked well, although some in..."
78,SR2026-0079,2026-04-01,Aalborg,Waste,75,71,2.5,4.2,52,23,5,2,26.4,Some users found the collection instructions c...
79,SR2026-0079,2026-04-01,Aalborg,Citizen Services,103,102,1.9,4.6,74,29,6,3,33.5,Friendly staff and a clear answer.

## Example 3.19.4 — Find repeated `record_id` values (continued)

**Website locator:** Example 3.19.4

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df.drop_duplicates(subset=["record_id"])

## Example 3.19.5 — Create a quality flag instead of deleting

**Website locator:** Example 3.19.5

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["flag_repeated_id"] = df["record_id"].duplicated(keep=False)

# Tutorial 3.20 — Standardising categories and text labels

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.20.1 — Inspect before changing

**Website locator:** Example 3.20.1

In [28]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df["city"].value_counts(dropna=False))

city
Aarhus          30
Copenhagen      29
Odense          29
Aalborg         28
 copenhagen      1
AALBORG          1
Odense           1
aarhus           1
Koebenhavn       1
Name: count, dtype: int64

## Example 3.20.2 — Inspect before changing (continued)

**Website locator:** Example 3.20.2

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df["service_type"].value_counts(dropna=False))

## Example 3.20.3 — Remove accidental spaces

**Website locator:** Example 3.20.3

In [30]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["city"] = df["city"].str.strip()
df["service_type"] = df["service_type"].str.strip()

## Example 3.20.4 — Standardise capitalisation

**Website locator:** Example 3.20.4

In [31]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["city"] = df["city"].str.title()
df["service_type"] = df["service_type"].str.title()

## Example 3.20.5 — Use a mapping dictionary for known variants

**Website locator:** Example 3.20.5

In [32]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

city_mapping = {
    "Kobenhavn": "Copenhagen",
    "København": "Copenhagen",
    "Cph": "Copenhagen"
}

df["city"] = df["city"].replace(city_mapping)

## Example 3.20.6 — Check the result

**Website locator:** Example 3.20.6

In [33]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df["city"].value_counts(dropna=False))
print(df["service_type"].value_counts(dropna=False))

city
Aarhus        31
Copenhagen    30
Odense        30
Aalborg       29
Koebenhavn     1
Name: count, dtype: int64
service_type
Transport              25
Waste                  25
Citizen Services       25
Employment             24
Housing                21
Employment Services     1
Name: count, dtype: int64

## Example 3.20.7 — Validate against an intended category list

**Website locator:** Example 3.20.7

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

valid_cities = ["Copenhagen", "Aarhus", "Odense", "Aalborg"]

invalid_city_mask = ~df["city"].isin(valid_cities) & df["city"].notna()
invalid_city_rows = df[invalid_city_mask]

invalid_city_rows

## Example 3.20.8 — Validate against an intended category list (continued)

**Website locator:** Example 3.20.8

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

valid_services = [
    "Housing",
    "Transport",
    "Employment",
    "Waste",
    "Citizen Services"
]

invalid_service_mask = (
    ~df["service_type"].isin(valid_services)
    & df["service_type"].notna()
)

invalid_service_rows = df[invalid_service_mask]
invalid_service_rows

# Tutorial 3.21 — Converting numeric columns safely

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.21.1 — Check data types

**Website locator:** Example 3.21.1

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df.dtypes)

## Example 3.21.2 — Check data types (continued)

**Website locator:** Example 3.21.2

In [34]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df["staff_hours"].dtype)

float64

## Example 3.21.3 — Why `astype(float)` may fail

**Website locator:** Example 3.21.3

In [35]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["staff_hours"].astype(float)

0      87.8
1      54.7
2      58.2
3      34.3
4      48.9
       ...
116    32.4
117    37.5
118    23.3
119    29.8
120    42.5
Name: staff_hours, Length: 121, dtype: float64

## Example 3.21.4 — Use `pd.to_numeric()` with `errors="coerce"`

**Website locator:** Example 3.21.4

In [37]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["staff_hours"] = pd.to_numeric(
    df["staff_hours"],
    errors="coerce"
)

## Example 3.21.5 — Identify what was changed to missing

**Website locator:** Example 3.21.5

In [40]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.
import re  # Imports regular-expression tools for transparent text cleaning.

staff_hours_before = df["staff_hours"].copy()

df["staff_hours"] = pd.to_numeric(
    df["staff_hours"],
    errors="coerce"
)

conversion_problem_mask = (
    staff_hours_before.notna()
    & df["staff_hours"].isna()
)

print(staff_hours_before[conversion_problem_mask])

Series([], Name: staff_hours, dtype: float64)

## Example 3.21.6 — Convert several intended numeric columns

**Website locator:** Example 3.21.6

In [39]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

numeric_columns = [
    "cases_received",
    "cases_resolved",
    "resolution_days",
    "satisfaction_score",
    "digital_cases",
    "in_person_cases",
    "repeat_contacts",
    "complaints_received",
    "staff_hours"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

## Example 3.21.7 — Check the new data types

**Website locator:** Example 3.21.7

In [41]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df[numeric_columns].dtypes)

cases_received           int64
cases_resolved           int64
resolution_days        float64
satisfaction_score     float64
digital_cases            int64
in_person_cases          int64
repeat_contacts          int64
complaints_received      int64
staff_hours            float64
dtype: object

# Tutorial 3.22 — Dates, ranges and impossible values

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.22.1 — Convert `report_month` to a date type

**Website locator:** Example 3.22.1

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df["report_month"].head(10))

## Example 3.22.2 — Convert `report_month` to a date type (continued)

**Website locator:** Example 3.22.2

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["report_month"] = pd.to_datetime(
    df["report_month"],
    errors="coerce"
)

## Example 3.22.3 — Find failed date conversions

**Website locator:** Example 3.22.3

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

invalid_date_rows = df[df["report_month"].isna()]
invalid_date_rows[["record_id", "report_month"]]

## Example 3.22.4 — Check a satisfaction scale

**Website locator:** Example 3.22.4

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

invalid_satisfaction_mask = (
    (df["satisfaction_score"] < 1)
    | (df["satisfaction_score"] > 5)
)

invalid_satisfaction = df[invalid_satisfaction_mask]
invalid_satisfaction[["record_id", "satisfaction_score"]]

## Example 3.22.5 — Check for negative counts

**Website locator:** Example 3.22.5

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

count_columns = [
    "cases_received",
    "cases_resolved",
    "digital_cases",
    "in_person_cases",
    "repeat_contacts",
    "complaints_received"
]

for column in count_columns:
    negative_mask = df[column] < 0
    print(column, "negative values:", negative_mask.sum())

## Example 3.22.6 — Inspect, do not instantly delete, outliers

**Website locator:** Example 3.22.6

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(df["resolution_days"].describe())

## Example 3.22.7 — Inspect, do not instantly delete, outliers (continued)

**Website locator:** Example 3.22.7

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

print(
    df[["record_id", "city", "service_type", "resolution_days"]]
    .sort_values("resolution_days", ascending=False)
    .head(10)
)

## Example 3.22.8 — Optional: use quantiles to find unusual values

**Website locator:** Example 3.22.8

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

q1 = df["resolution_days"].quantile(0.25)
q3 = df["resolution_days"].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

possible_outliers = df[
    (df["resolution_days"] < lower_bound)
    | (df["resolution_days"] > upper_bound)
]

possible_outliers[["record_id", "resolution_days"]]

# Tutorial 3.23 — Cross-column consistency checks

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.23.1 — Resolved cases should not exceed received cases

**Website locator:** Example 3.23.1

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

resolved_too_high_mask = (
    df["cases_resolved"] > df["cases_received"]
)

resolved_too_high = df[resolved_too_high_mask]

resolved_too_high[[
    "record_id",
    "cases_received",
    "cases_resolved"
]]

## Example 3.23.2 — Digital + in-person cases should match total received cases

**Website locator:** Example 3.23.2

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["channel_total"] = (
    df["digital_cases"] + df["in_person_cases"]
)

## Example 3.23.3 — Digital + in-person cases should match total received cases (continued)

**Website locator:** Example 3.23.3

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

channel_mismatch_mask = (
    df["channel_total"] != df["cases_received"]
)

channel_mismatches = df[channel_mismatch_mask]

channel_mismatches[[
    "record_id",
    "cases_received",
    "digital_cases",
    "in_person_cases",
    "channel_total"
]]

## Example 3.23.4 — Missing-value caution

**Website locator:** Example 3.23.4

In [43]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

required_available = df[[
    "cases_received",
    "digital_cases",
    "in_person_cases"
]].notna().all(axis=1)

channel_mismatch_mask = (
    required_available
    & (
        df["digital_cases"]
        + df["in_person_cases"]
        != df["cases_received"]
    )
)

## Example 3.23.5 — Repeat contacts should not exceed received cases

**Website locator:** Example 3.23.5

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

repeat_too_high_mask = (
    df["repeat_contacts"] > df["cases_received"]
)

repeat_too_high = df[repeat_too_high_mask]
repeat_too_high[[
    "record_id",
    "cases_received",
    "repeat_contacts"
]]

## Example 3.23.6 — Create flags instead of deleting records

**Website locator:** Example 3.23.6

In [45]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["flag_resolved_gt_received"] = (
    df["cases_resolved"] > df["cases_received"]
)

df["flag_channel_mismatch"] = channel_mismatch_mask

df["flag_repeat_gt_received"] = (
    df["repeat_contacts"] > df["cases_received"]
)

## Example 3.23.7 — Create flags instead of deleting records (continued)

**Website locator:** Example 3.23.7

In [46]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

quality_flags = [
    "flag_resolved_gt_received",
    "flag_channel_mismatch",
    "flag_repeat_gt_received"
]

print(df[quality_flags].sum())

flag_resolved_gt_received    3
flag_channel_mismatch        2
flag_repeat_gt_received      2
dtype: int64

# Tutorial 3.24 — Making cleaning decisions transparently

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.24.1 — Worked code example

**Website locator:** Example 3.24.1

In [48]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

clean_everything_correctly()

NameError: name 'clean_everything_correctly' is not defined

## Example 3.24.2 — Correct

**Website locator:** Example 3.24.2

In [49]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["city"] = df["city"].str.strip()

## Example 3.24.3 — Convert

**Website locator:** Example 3.24.3

In [50]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["staff_hours"] = pd.to_numeric(
    df["staff_hours"],
    errors="coerce"
)

## Example 3.24.4 — Flag and retain

**Website locator:** Example 3.24.4

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["flag_invalid_satisfaction"] = (
    (df["satisfaction_score"] < 1)
    | (df["satisfaction_score"] > 5)
)

## Example 3.24.5 — Exclude from a specific analysis

**Website locator:** Example 3.24.5

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

valid_satisfaction = df[
    df["satisfaction_score"].between(1, 5)
].copy()

## Example 3.24.6 — Create a simple transformation log

**Website locator:** Example 3.24.6

In [52]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

transformation_log = []

[]

## Example 3.24.7 — Create a simple transformation log (continued)

**Website locator:** Example 3.24.7

In [53]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

transformation_log.append({
    "step": 1,
    "column": "city",
    "issue": "Leading/trailing whitespace",
    "action": "Applied str.strip()",
    "reason": "Whitespace created duplicate-looking categories",
    "rows_affected": "Check with before/after comparison",
    "possible_effect": "Reduces artificial fragmentation of city categories"
})

## Example 3.24.8 — Create a simple transformation log (continued)

**Website locator:** Example 3.24.8

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

log_df = pd.DataFrame(transformation_log)
log_df

## Example 3.24.9 — Better: calculate rows affected

**Website locator:** Example 3.24.9

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

city_before = df["city"].copy()

## Example 3.24.10 — Better: calculate rows affected (continued)

**Website locator:** Example 3.24.10

In [ ]:
# Imports are repeated intentionally so this code block is easier to copy into a fresh notebook cell.
import pandas as pd  # Imports pandas for working with table-shaped data.

df["city"] = df["city"].str.strip()

## Example 3.24.11 — Integrated cleaning, inspection and transformation log

**Website locator:** Example 3.24.11

**Situation:** A researcher has a four-row synthetic service table. City names contain accidental spaces, one staff-hours value is written as `unknown`, one satisfaction score is outside the allowed 1–5 range and another score is missing.

**What this example is for:** Combine the four responses from Tutorial 3.24 in one runnable example: correct formatting, convert a value, flag and retain a questionable record, and exclude rows from one specific analysis. Count affected rows and record a reason for each decision.

**Learning outcome:** Explain and document how a cleaning choice changes the data available for analysis. This supports the module objectives on writing simple scripts, handling data and assessing data quality and reliability.

**Run it on its own:** This cell creates its own four-row table, so it needs only pandas and no CSV download. It uses `example_raw` and `example_df` to keep the recurring course table `df` available for the following tutorials.

**Read the example in this order:**
1. Create the synthetic data and a separate working copy.
2. Remove edge spaces from city labels and count the changed rows.
3. Convert staff hours to numbers and count values that become missing.
4. Flag scores outside 1–5, while counting missing scores separately.
5. Create a separate table for the satisfaction analysis.
6. Build the transformation log and print the original table, working table, analysis subset and log together.

**Before you run it:** Predict how many city labels will change, how many staff-hours values will become missing, how many scores will be flagged and how many rows the satisfaction analysis will exclude.

In [1]:
import pandas as pd

# Small example dataset, so this code runs on its own.
example_raw = pd.DataFrame({
    "city": [" Copenhagen ", "Aarhus", " Aalborg", "Odense "],
    "staff_hours": ["40", "unknown", "25", "30"],
    "satisfaction_score": [4, 7, 3, None]
})

# Work on a copy to preserve the original data.
# example_df keeps this small demonstration separate from the course table df.
example_df = example_raw.copy()


# 1. CORRECT: remove spaces around city names.
city_before = example_df["city"].copy()
example_df["city"] = example_df["city"].str.strip()

# Count rows whose city name changed.
city_changed = (
    city_before.fillna("") != example_df["city"].fillna("")
).sum()


# 2. CONVERT: turn staff hours into numbers.
hours_before = example_df["staff_hours"].copy()
example_df["staff_hours"] = pd.to_numeric(
    example_df["staff_hours"],
    errors="coerce"  # Unconvertible text becomes NaN (missing).
)

# Count values that became missing during conversion.
hours_failed = (
    hours_before.notna() & example_df["staff_hours"].isna()
).sum()


# 3. FLAG AND RETAIN: identify scores outside the allowed range.
# Scores should be between 1 and 5. Keep questionable rows for review.
example_df["flag_invalid_satisfaction"] = (
    (example_df["satisfaction_score"] < 1)
    | (example_df["satisfaction_score"] > 5)
)

# Missing scores are checked separately from out-of-range scores.
invalid_scores = example_df["flag_invalid_satisfaction"].sum()
missing_scores = example_df["satisfaction_score"].isna().sum()


# 4. EXCLUDE FOR ONE ANALYSIS: select valid satisfaction scores.
# This creates a separate table. It does not delete rows from example_df.
example_valid_satisfaction = example_df[
    example_df["satisfaction_score"].between(1, 5)
].copy()

scores_excluded = len(example_df) - len(example_valid_satisfaction)


# Record what happened, how many rows it affected and why.
example_log = pd.DataFrame([
    {
        "action": "Removed spaces from city names",
        "rows_affected": int(city_changed),
        "reason": "Avoid separate categories caused by accidental spaces"
    },
    {
        "action": "Converted staff hours to numeric",
        "rows_affected": int(hours_failed),
        "reason": "Expose unconvertible values as missing"
    },
    {
        "action": "Flagged out-of-range satisfaction scores",
        "rows_affected": int(invalid_scores),
        "reason": "Retain questionable values for source verification"
    },
    {
        "action": "Excluded scores from satisfaction analysis",
        "rows_affected": int(scores_excluded),
        "reason": "This analysis requires a score between 1 and 5"
    }
])


# Print all results together.
print("ORIGINAL DATA")
print(example_raw.to_string(index=False))

print("\nWORKING DATA AFTER CLEANING AND INSPECTION")
print(example_df.to_string(index=False))

print("\nVALID ROWS FOR SATISFACTION ANALYSIS")
print(example_valid_satisfaction.to_string(index=False))

print("\nMissing satisfaction scores:", missing_scores)

print("\nTRANSFORMATION LOG")
print(example_log.to_string(index=False))

ORIGINAL DATA
        city staff_hours  satisfaction_score
 Copenhagen           40                 4.0
      Aarhus     unknown                 7.0
     Aalborg          25                 3.0
     Odense           30                 NaN

WORKING DATA AFTER CLEANING AND INSPECTION
      city  staff_hours  satisfaction_score  flag_invalid_satisfaction
Copenhagen         40.0                 4.0                      False
    Aarhus          NaN                 7.0                       True
   Aalborg         25.0                 3.0                      False
    Odense         30.0                 NaN                      False

VALID ROWS FOR SATISFACTION ANALYSIS
      city  staff_hours  satisfaction_score  flag_invalid_satisfaction
Copenhagen         40.0                 4.0                      False
   Aalborg         25.0                 3.0                      False

Missing satisfaction scores: 1

TRANSFORMATION LOG
                                    action  rows_affected                                                reason
            Removed spaces from city names              3 Avoid separate categories caused by accidental spaces
          Converted staff hours to numeric              1                Expose unconvertible values as missing
  Flagged out-of-range satisfaction scores              1    Retain questionable values for source verification
Excluded scores from satisfaction analysis              2        This analysis requires a score between 1 and 5

### Expected results and interpretation

| Action or check | Expected result | What it means |
|---|---:|---|
| City labels corrected | 3 rows | Copenhagen, Aalborg and Odense lose accidental edge spaces. |
| Staff-hours values becoming missing | 1 value | `unknown` becomes `NaN`. It does not become zero. |
| Out-of-range satisfaction scores flagged | 1 row | Aarhus has a score of 7. The row remains in `example_df`. |
| Missing satisfaction scores | 1 value | Odense has no recorded score. Missing is checked separately. |
| Rows excluded from the satisfaction subset | 2 rows | The score of 7 and the missing score cannot enter this analysis. |
| Rows retained for the satisfaction analysis | 2 rows | Copenhagen and Aalborg have scores between 1 and 5. |

The transformation log prints the affected-row counts **3, 1, 1 and 2** for its four actions. The working table still contains all four rows, and the raw table stays unchanged. These counts refer to different operations and can overlap; adding them does not give a count of unique problem rows.

**Interpret carefully:** A `False` value in `flag_invalid_satisfaction` only means the score was not flagged as outside the range. A missing score also receives `False` here, so it still needs the separate missing-value check. Successful numeric conversion does not prove that a value is accurate, and a score of 7 needs source verification before correction. The satisfaction subset represents only rows with an available in-range score.

### Modify, break, repair and reflect

- **Modify:** Change the Aarhus score from `7` to `5`. Predict how the flag count and excluded-row count will change, then run the cell again.
- **Break and repair:** Change `errors="coerce"` to `errors="raise"`. Observe the error caused by `unknown`, explain it and restore `"coerce"`.
- **Reflect:** Why would replacing a missing satisfaction score with zero misrepresent the record? What should the log explain if you later exclude a row from another analysis?

**Common error:** In this example, `example_log` is already a DataFrame. To add another action, add a dictionary inside `pd.DataFrame([...])` and rerun the cell. The earlier tutorial uses a list with `.append()`; the two objects require different operations.

# Tutorial 3.25 — Why text needs preparation

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

# Tutorial 3.26 — NLTK setup and tokenisation

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.26.1 — Import NLTK

**Website locator:** Example 3.26.1

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import nltk

# MAIN DEMONSTRATION
print("NLTK imported successfully. Version:", nltk.__version__)

NLTK imported successfully. Version: 3.10.3

**What to inspect:** Import NLTK and print the installed version. Importing a library makes its tools available; it does not tokenise any text.

## Example 3.26.2 — Import NLTK (continued)

**Website locator:** Example 3.26.2

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# MAIN DEMONSTRATION
print("Imports ready: word_tokenize and stopwords.")

Imports ready: word_tokenize and stopwords.

**What to inspect:** Import the tokenizer and stop-word corpus interface. The printed confirmation concerns imports only; resource checks appear in later complete blocks.

## Example 3.26.3 — Download the required resources

**Website locator:** Example 3.26.3

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
print("Resources ready: punkt, punkt_tab and English stop words.")
print("Tokens:", word_tokenize("Service was quick!"))

Resources ready: punkt, punkt_tab and English stop words.
Tokens: ['Service', 'was', 'quick', '!']

**What to inspect:** Check the required NLTK resources, download any missing resource, and verify setup by tokenising a short sentence. A first download requires internet access.

## Example 3.26.4 — First tokenisation example

**Website locator:** Example 3.26.4

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
text = 'The staff were helpful, but the process was slow.'
tokens = word_tokenize(text)
print("Original:", text)
print("Tokens:", tokens)

Original: The staff were helpful, but the process was slow.
Tokens: ['The', 'staff', 'were', 'helpful', ',', 'but', 'the', 'process', 'was', 'slow', '.']

**What to inspect:** Create the sentence in this block and print both the input and token list, including punctuation.

## Example 3.26.5 — Lowercase before or after tokenisation?

**Website locator:** Example 3.26.5

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
text = 'The staff were helpful, but the process was slow.'
text_lower = text.lower()
tokens = word_tokenize(text_lower)
print("Original:", text)
print("Lowercased tokens:", tokens)

Original: The staff were helpful, but the process was slow.
Lowercased tokens: ['the', 'staff', 'were', 'helpful', ',', 'but', 'the', 'process', 'was', 'slow', '.']

**What to inspect:** Define the input locally, lowercase it before tokenisation and compare the printed input with the resulting tokens.

## Example 3.26.6 — Lowercase before or after tokenisation? (continued)

**Website locator:** Example 3.26.6

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
text = 'The staff were helpful, but the process was slow.'
tokens = [token.lower() for token in word_tokenize(text)]
print("Original:", text)
print("Tokens lowercased after tokenisation:", tokens)

Original: The staff were helpful, but the process was slow.
Tokens lowercased after tokenisation: ['the', 'staff', 'were', 'helpful', ',', 'but', 'the', 'process', 'was', 'slow', '.']

**What to inspect:** Repeat the same input independently and lowercase the tokens after tokenisation. Compare this output with Example 3.26.5.

## Example 3.26.7 — Handle a missing feedback value safely

**Website locator:** Example 3.26.7

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
text = None  # A deliberately missing value, not the word "None".
try:
    print(word_tokenize(text))
except TypeError as error:
    print("Expected TypeError caught:", error)
    print("A missing-value check is needed before tokenisation.")

Expected TypeError caught: expected string or bytes-like object, got 'NoneType'
A missing-value check is needed before tokenisation.

**What to inspect:** Demonstrate the missing-value error inside try/except. The error message is visible, but this deliberately faulty call does not stop the notebook. The following examples show the repair.

## Example 3.26.8 — Handle a missing feedback value safely (continued)

**Website locator:** Example 3.26.8

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Missing feedback has no tokens, but it remains missing in the raw column.
def tokenize_feedback(text):
    if pd.isna(text):
        return []
    return word_tokenize(str(text).lower())

# MAIN DEMONSTRATION
print("Present text:", tokenize_feedback("Service was quick!"))
print("Missing text:", tokenize_feedback(None))

Present text: ['service', 'was', 'quick', '!']
Missing text: []

**What to inspect:** Define and call a missing-safe tokenizer in the same block. A return statement supplies a result; print makes the returned result visible.

## Example 3.26.9 — Handle a missing feedback value safely (continued)

**Website locator:** Example 3.26.9

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Missing feedback has no tokens, but it remains missing in the raw column.
def tokenize_feedback(text):
    if pd.isna(text):
        return []
    return word_tokenize(str(text).lower())

# MAIN DEMONSTRATION
for text in ["Service was quick!", None, ""]:
    print(repr(text), "=>", tokenize_feedback(text))

'Service was quick!' => ['service', 'was', 'quick', '!']
None => []
'' => []

**What to inspect:** Recreate the function locally and print results for a sentence, a missing value and an empty string. Raw missingness and an empty token list carry different meanings.

## Example 3.26.10 — Apply the function to the DataFrame

**Website locator:** Example 3.26.10

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Missing feedback has no tokens, but it remains missing in the raw column.
def tokenize_feedback(text):
    if pd.isna(text):
        return []
    return word_tokenize(str(text).lower())

# MAIN DEMONSTRATION
df["feedback_tokens_raw"] = df["feedback"].apply(tokenize_feedback)
print(df[["feedback", "feedback_tokens_raw"]].head(5).to_string(index=False))
print("Source feedback missing:", int(df["feedback"].isna().sum()))

                                                                       feedback                                                                            feedback_tokens_raw
The guidance was clear, but the supporting-document requirements caused delays. [the, guidance, was, clear, ,, but, the, supporting-document, requirements, caused, delays, .]
             Several users asked for clearer information about service changes.                 [several, users, asked, for, clearer, information, about, service, changes, .]
                              Useful advice and a friendly response from staff.                                   [useful, advice, and, a, friendly, response, from, staff, .]
                   Helpful guidance, but some users reported delayed follow-up.                      [helpful, guidance, ,, but, some, users, reported, delayed, follow-up, .]
                          The response was fast and the information was useful.                              [the, response, was, fast, and, the, information, was, useful, .]
Source feedback missing: 3

**What to inspect:** Load the course CSV and define all required tools within this block. Apply the tokenizer and print a bounded raw-text/token comparison plus the missing-feedback count.

## Example 3.26.11 — Apply the function to the DataFrame (continued)

**Website locator:** Example 3.26.11

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Missing feedback has no tokens, but it remains missing in the raw column.
def tokenize_feedback(text):
    if pd.isna(text):
        return []
    return word_tokenize(str(text).lower())

# MAIN DEMONSTRATION
df["feedback_tokens_raw"] = df["feedback"].apply(tokenize_feedback)
print(df[["feedback", "feedback_tokens_raw"]].head(10).to_string(index=False))
print("Source feedback missing:", int(df["feedback"].isna().sum()))

                                                                         feedback                                                                                feedback_tokens_raw
  The guidance was clear, but the supporting-document requirements caused delays.     [the, guidance, was, clear, ,, but, the, supporting-document, requirements, caused, delays, .]
               Several users asked for clearer information about service changes.                     [several, users, asked, for, clearer, information, about, service, changes, .]
                                Useful advice and a friendly response from staff.                                       [useful, advice, and, a, friendly, response, from, staff, .]
                     Helpful guidance, but some users reported delayed follow-up.                          [helpful, guidance, ,, but, some, users, reported, delayed, follow-up, .]
                            The response was fast and the information was useful.                                  [the, response, was, fast, and, the, information, was, useful, .]
Helpful staff explained the housing process, although the waiting time felt long. [helpful, staff, explained, the, housing, process, ,, although, the, waiting, time, felt, long, .]
               Several users asked for clearer information about service changes.                     [several, users, asked, for, clearer, information, about, service, changes, .]
       The answer was useful, although the waiting time was longer than expected.        [the, answer, was, useful, ,, although, the, waiting, time, was, longer, than, expected, .]
        Collection information was easy to understand and the response was quick.            [collection, information, was, easy, to, understand, and, the, response, was, quick, .]
                                               Friendly staff and a clear answer.                                                        [friendly, staff, and, a, clear, answer, .]
Source feedback missing: 3

**What to inspect:** Load the course CSV and define all required tools within this block. Apply the tokenizer and print a bounded raw-text/token comparison plus the missing-feedback count.

## Example 3.26.12 — Common error: `LookupError`

**Website locator:** Example 3.26.12

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
print("Tokenizer resource check passed.")
print(word_tokenize("A fresh runtime can tokenise this sentence."))
print("English stop-word list loaded:", len(stopwords.words("english")), "entries")

Tokenizer resource check passed.
['A', 'fresh', 'runtime', 'can', 'tokenise', 'this', 'sentence', '.']
English stop-word list loaded: 198 entries

**What to inspect:** Use the resource checks as a repair for LookupError. The printed token list verifies that tokenisation works after setup.

# Tutorial 3.27 — Lowercasing, punctuation and stop words

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.27.1 — Lowercasing

**Website locator:** Example 3.27.1

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
text = "Helpful helpful HELPFUL"
print("Before:", word_tokenize(text))
print("After:", [token.lower() for token in word_tokenize(text)])

Before: ['Helpful', 'helpful', 'HELPFUL']
After: ['helpful', 'helpful', 'helpful']

**What to inspect:** Show how lowercasing merges capitalisation variants. It removes information about emphasis and proper names.

## Example 3.27.2 — Remove punctuation using `isalpha()`

**Website locator:** Example 3.27.2

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
text = "Fast service, but 2 forms were confusing!"
tokens = word_tokenize(text.lower())
alphabetic_tokens = [token for token in tokens if token.isalpha()]
print("Before:", tokens)
print("Alphabetic tokens:", alphabetic_tokens)

Before: ['fast', 'service', ',', 'but', '2', 'forms', 'were', 'confusing', '!']
Alphabetic tokens: ['fast', 'service', 'but', 'forms', 'were', 'confusing']

**What to inspect:** Compare tokens before and after isalpha(). This rule removes the digit 2 as well as punctuation, so it can remove relevant information.

## Example 3.27.3 — Load English stop words

**Website locator:** Example 3.27.3

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
stop_words = set(stopwords.words("english"))
print("Stop-word entries:", len(stop_words))
print("First 15 alphabetically:", sorted(stop_words)[:15])

Stop-word entries: 198
First 15 alphabetically: ['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't"]

**What to inspect:** Load the complete English stop-word set and print its size and a sorted sample rather than silently assigning a variable.

## Example 3.27.4 — The negation problem

**Website locator:** Example 3.27.4

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
stop_words = set(stopwords.words("english"))
for word in ["not", "no", "nor"]:
    print(f"{word!r} in default stop words:", word in stop_words)

'not' in default stop words: True
'no' in default stop words: True
'nor' in default stop words: True

**What to inspect:** Create the default set locally and inspect all three negation words explicitly.

## Example 3.27.5 — The negation problem (continued)

**Website locator:** Example 3.27.5

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# MAIN DEMONSTRATION
stop_words = set(stopwords.words("english"))
print("Before:", {word: word in stop_words for word in ["not", "no", "nor"]})
stop_words.difference_update({"not", "no", "nor"})
print("After:", {word: word in stop_words for word in ["not", "no", "nor"]})

Before: {'not': True, 'no': True, 'nor': True}
After: {'not': False, 'no': False, 'nor': False}

**What to inspect:** Print membership before and after removing negation words from the stop-word set. Removing a word from this set preserves it in the prepared tokens.

## Example 3.27.6 — Build the cleaning function

**Website locator:** Example 3.27.6

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]

# MAIN DEMONSTRATION
example = "The wait was not long."
print("Original:", example)
print("Prepared tokens:", prepare_feedback(example))
print("Missing input:", prepare_feedback(None))

Original: The wait was not long.
Prepared tokens: ['wait', 'not', 'long']
Missing input: []

**What to inspect:** Define the complete cleaning function and call it immediately. The function handles missing values, keeps alphabetic tokens and preserves not/no/nor.

## Example 3.27.7 — Test the function before applying it to the whole dataset

**Website locator:** Example 3.27.7

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]

# MAIN DEMONSTRATION
for example in ["The wait was not long.", "The process took forever!", None]:
    print(repr(example), "=>", prepare_feedback(example))

'The wait was not long.' => ['wait', 'not', 'long']
'The process took forever!' => ['process', 'took', 'forever']
None => []

**What to inspect:** Define the function in this block and print a few tests before applying it to a dataset. Token preparation does not determine sentiment.

## Example 3.27.8 — Apply the function

**Website locator:** Example 3.27.8

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))

# MAIN DEMONSTRATION
print(df[["record_id", "feedback", "feedback_tokens", "feedback_clean"]].head(5).to_string(index=False))
print("Original feedback preserved:", df["feedback"].equals(df_raw["feedback"]))

  record_id                                                                        feedback                                                 feedback_tokens                                          feedback_clean
SR2026-0001 The guidance was clear, but the supporting-document requirements caused delays.                 [guidance, clear, requirements, caused, delays]               guidance clear requirements caused delays
SR2026-0002              Several users asked for clearer information about service changes. [several, users, asked, clearer, information, service, changes] several users asked clearer information service changes
SR2026-0003                               Useful advice and a friendly response from staff.                     [useful, advice, friendly, response, staff]                   useful advice friendly response staff
SR2026-0004                    Helpful guidance, but some users reported delayed follow-up.                   [helpful, guidance, users, reported, delayed]                 helpful guidance users reported delayed
SR2026-0005                           The response was fast and the information was useful.                           [response, fast, information, useful]                        response fast information useful
Original feedback preserved: True

**What to inspect:** Load the source, define the preparation function and derive tokens and joined text within this block. Print the raw and prepared representations together and verify that feedback remains unchanged.

## Example 3.27.9 — Apply the function (continued)

**Website locator:** Example 3.27.9

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))

# MAIN DEMONSTRATION
print(df[["record_id", "feedback", "feedback_tokens", "feedback_clean"]].head(15).to_string(index=False))
print("Original feedback preserved:", df["feedback"].equals(df_raw["feedback"]))

  record_id                                                                           feedback                                                                    feedback_tokens                                                          feedback_clean
SR2026-0001    The guidance was clear, but the supporting-document requirements caused delays.                                    [guidance, clear, requirements, caused, delays]                               guidance clear requirements caused delays
SR2026-0002                 Several users asked for clearer information about service changes.                    [several, users, asked, clearer, information, service, changes]                 several users asked clearer information service changes
SR2026-0003                                  Useful advice and a friendly response from staff.                                        [useful, advice, friendly, response, staff]                                   useful advice friendly response staff
SR2026-0004                       Helpful guidance, but some users reported delayed follow-up.                                      [helpful, guidance, users, reported, delayed]                                 helpful guidance users reported delayed
SR2026-0005                              The response was fast and the information was useful.                                              [response, fast, information, useful]                                        response fast information useful
SR2026-0006  Helpful staff explained the housing process, although the waiting time felt long. [helpful, staff, explained, housing, process, although, waiting, time, felt, long] helpful staff explained housing process although waiting time felt long
SR2026-0007                 Several users asked for clearer information about service changes.                    [several, users, asked, clearer, information, service, changes]                 several users asked clearer information service changes
SR2026-0008         The answer was useful, although the waiting time was longer than expected.                        [answer, useful, although, waiting, time, longer, expected]                     answer useful although waiting time longer expected
SR2026-0009          Collection information was easy to understand and the response was quick.                       [collection, information, easy, understand, response, quick]                   collection information easy understand response quick
SR2026-0010                                                 Friendly staff and a clear answer.                                                   [friendly, staff, clear, answer]                                             friendly staff clear answer
SR2026-0011 The online application was useful, but several steps were difficult to understand.               [online, application, useful, several, steps, difficult, understand]            online application useful several steps difficult understand
SR2026-0012 The response was quick, but route-change information was difficult to find online.                            [response, quick, information, difficult, find, online]                        response quick information difficult find online
SR2026-0013                                  Useful advice and a friendly response from staff.                                        [useful, advice, friendly, response, staff]                                   useful advice friendly response staff
SR2026-0014                       Helpful guidance, but some users reported delayed follow-up.                                      [helpful, guidance, users, reported, delayed]                                 helpful guidance users reported delayed
SR2026-0015                              The response was fast and the information was useful.                                              [response, fast, information, useful]                                        response fast information useful
Original feedback preserved: True

**What to inspect:** Load the source, define the preparation function and derive tokens and joined text within this block. Print the raw and prepared representations together and verify that feedback remains unchanged.

## Example 3.27.10 — Create an optional cleaned-text string

**Website locator:** Example 3.27.10

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))

# MAIN DEMONSTRATION
print(df[["record_id", "feedback", "feedback_tokens", "feedback_clean"]].head(5).to_string(index=False))
print("Original feedback preserved:", df["feedback"].equals(df_raw["feedback"]))

  record_id                                                                        feedback                                                 feedback_tokens                                          feedback_clean
SR2026-0001 The guidance was clear, but the supporting-document requirements caused delays.                 [guidance, clear, requirements, caused, delays]               guidance clear requirements caused delays
SR2026-0002              Several users asked for clearer information about service changes. [several, users, asked, clearer, information, service, changes] several users asked clearer information service changes
SR2026-0003                               Useful advice and a friendly response from staff.                     [useful, advice, friendly, response, staff]                   useful advice friendly response staff
SR2026-0004                    Helpful guidance, but some users reported delayed follow-up.                   [helpful, guidance, users, reported, delayed]                 helpful guidance users reported delayed
SR2026-0005                           The response was fast and the information was useful.                           [response, fast, information, useful]                        response fast information useful
Original feedback preserved: True

**What to inspect:** Load the source, define the preparation function and derive tokens and joined text within this block. Print the raw and prepared representations together and verify that feedback remains unchanged.

## Example 3.27.11 — Create an optional cleaned-text string (continued)

**Website locator:** Example 3.27.11

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))

# MAIN DEMONSTRATION
print(df[["record_id", "feedback", "feedback_tokens", "feedback_clean"]].head(10).to_string(index=False))
print("Original feedback preserved:", df["feedback"].equals(df_raw["feedback"]))

  record_id                                                                          feedback                                                                    feedback_tokens                                                          feedback_clean
SR2026-0001   The guidance was clear, but the supporting-document requirements caused delays.                                    [guidance, clear, requirements, caused, delays]                               guidance clear requirements caused delays
SR2026-0002                Several users asked for clearer information about service changes.                    [several, users, asked, clearer, information, service, changes]                 several users asked clearer information service changes
SR2026-0003                                 Useful advice and a friendly response from staff.                                        [useful, advice, friendly, response, staff]                                   useful advice friendly response staff
SR2026-0004                      Helpful guidance, but some users reported delayed follow-up.                                      [helpful, guidance, users, reported, delayed]                                 helpful guidance users reported delayed
SR2026-0005                             The response was fast and the information was useful.                                              [response, fast, information, useful]                                        response fast information useful
SR2026-0006 Helpful staff explained the housing process, although the waiting time felt long. [helpful, staff, explained, housing, process, although, waiting, time, felt, long] helpful staff explained housing process although waiting time felt long
SR2026-0007                Several users asked for clearer information about service changes.                    [several, users, asked, clearer, information, service, changes]                 several users asked clearer information service changes
SR2026-0008        The answer was useful, although the waiting time was longer than expected.                        [answer, useful, although, waiting, time, longer, expected]                     answer useful although waiting time longer expected
SR2026-0009         Collection information was easy to understand and the response was quick.                       [collection, information, easy, understand, response, quick]                   collection information easy understand response quick
SR2026-0010                                                Friendly staff and a clear answer.                                                   [friendly, staff, clear, answer]                                             friendly staff clear answer
Original feedback preserved: True

**What to inspect:** Load the source, define the preparation function and derive tokens and joined text within this block. Print the raw and prepared representations together and verify that feedback remains unchanged.

## Example 3.27.12 — Do not overwrite the raw feedback

**Website locator:** Example 3.27.12

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))

# MAIN DEMONSTRATION
# Demonstrate the destructive approach on a disposable copy only.
unsafe_copy = df.copy(deep=True)
unsafe_copy["feedback"] = unsafe_copy["feedback"].apply(prepare_feedback)
print("Original field would now contain token lists:")
print(unsafe_copy[["feedback"]].head(3).to_string(index=False))
print("\nSafer separate columns:")
print(df[["feedback", "feedback_clean"]].head(3).to_string(index=False))
print("Actual working feedback preserved:", df["feedback"].equals(df_raw["feedback"]))

Original field would now contain token lists:
                                                       feedback
                [guidance, clear, requirements, caused, delays]
[several, users, asked, clearer, information, service, changes]
                    [useful, advice, friendly, response, staff]

Safer separate columns:
                                                                       feedback                                          feedback_clean
The guidance was clear, but the supporting-document requirements caused delays.               guidance clear requirements caused delays
             Several users asked for clearer information about service changes. several users asked clearer information service changes
                              Useful advice and a friendly response from staff.                   useful advice friendly response staff
Actual working feedback preserved: True

**What to inspect:** Illustrate the unsafe overwrite on a disposable copy, so running this warning example cannot destroy the working feedback. Compare it with the safer separate-column approach.

## Example 3.27.13 — Compare before and after

**Website locator:** Example 3.27.13

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)

# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))

# MAIN DEMONSTRATION
print(df[["record_id", "feedback", "feedback_tokens", "feedback_clean"]].head(10).to_string(index=False))
print("Original feedback preserved:", df["feedback"].equals(df_raw["feedback"]))

  record_id                                                                          feedback                                                                    feedback_tokens                                                          feedback_clean
SR2026-0001   The guidance was clear, but the supporting-document requirements caused delays.                                    [guidance, clear, requirements, caused, delays]                               guidance clear requirements caused delays
SR2026-0002                Several users asked for clearer information about service changes.                    [several, users, asked, clearer, information, service, changes]                 several users asked clearer information service changes
SR2026-0003                                 Useful advice and a friendly response from staff.                                        [useful, advice, friendly, response, staff]                                   useful advice friendly response staff
SR2026-0004                      Helpful guidance, but some users reported delayed follow-up.                                      [helpful, guidance, users, reported, delayed]                                 helpful guidance users reported delayed
SR2026-0005                             The response was fast and the information was useful.                                              [response, fast, information, useful]                                        response fast information useful
SR2026-0006 Helpful staff explained the housing process, although the waiting time felt long. [helpful, staff, explained, housing, process, although, waiting, time, felt, long] helpful staff explained housing process although waiting time felt long
SR2026-0007                Several users asked for clearer information about service changes.                    [several, users, asked, clearer, information, service, changes]                 several users asked clearer information service changes
SR2026-0008        The answer was useful, although the waiting time was longer than expected.                        [answer, useful, although, waiting, time, longer, expected]                     answer useful although waiting time longer expected
SR2026-0009         Collection information was easy to understand and the response was quick.                       [collection, information, easy, understand, response, quick]                   collection information easy understand response quick
SR2026-0010                                                Friendly staff and a clear answer.                                                   [friendly, staff, clear, answer]                                             friendly staff clear answer
Original feedback preserved: True

**What to inspect:** Load the source, define the preparation function and derive tokens and joined text within this block. Print the raw and prepared representations together and verify that feedback remains unchanged.

## Example 3.27.14 — Optional extension: custom stop words

**Website locator:** Example 3.27.14

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]

# MAIN DEMONSTRATION
text = "The service was helpful, but the service was not quick."
custom_stop_words = stop_words | {"service"}
tokens = word_tokenize(text.lower())
before = [t for t in tokens if t.isalpha() and t not in stop_words]
after = [t for t in tokens if t.isalpha() and t not in custom_stop_words]
print("Original:", text)
print("Course rule:", before)
print("Also excluding 'service':", after)
print("Decision: omit 'service' only if its frequency is irrelevant to the question.")

Original: The service was helpful, but the service was not quick.
Course rule: ['service', 'helpful', 'service', 'not', 'quick']
Also excluding 'service': ['helpful', 'not', 'quick']
Decision: omit 'service' only if its frequency is irrelevant to the question.

**What to inspect:** Compare the standard course rule with one explicitly chosen domain stop word. This is a demonstrative choice, not a default rule for every analysis.

# Tutorial 3.28 — Build the cleaned dataset and transformation log

Use the matching website section for the full explanation, expected output, interpretation and reflection prompts.

## Example 3.28.1 — Start again from the raw file

**Website locator:** Example 3.28.1

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

# MAIN DEMONSTRATION
print("Raw rows and columns:", df_raw.shape)
print("Working copy initially matches:", df.equals(df_raw))
print(df.head(3).to_string(index=False))

Raw rows and columns: (121, 14)
Working copy initially matches: True
  record_id report_month       city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                        feedback
SR2026-0001   2026-01-01 Copenhagen      Housing             130             116             8.0                 3.5             88               42               17                   10         87.8 The guidance was clear, but the supporting-document requirements caused delays.
SR2026-0002   2026-01-01 Copenhagen    Transport             124             110             5.1                 3.9             92               32               10                    8         54.7              Several users asked for clearer information about service changes.
SR2026-0003   2026-01-01 Copenhagen   Employment             105              93             5.5                 3.9             73               32               14                    5         58.2                               Useful advice and a friendly response from staff.

**What to inspect:** Start again from the canonical raw CSV, make a separate copy and print its shape and first three rows. No previous import or cleaning cell is needed.

## Example 3.28.2 — Create the transformation log

**Website locator:** Example 3.28.2

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.

# MAIN DEMONSTRATION
transformation_log = []
log_df = pd.DataFrame(transformation_log, columns=["step", "variable", "action", "rationale", "rows_affected", "reversible", "notes"])
print("Log initialised. Entries:", len(log_df))
print(log_df.to_string(index=False))
print("No transformations have been recorded yet.")

Log initialised. Entries: 0
Empty DataFrame
Columns: [step, variable, action, rationale, rows_affected, reversible, notes]
Index: []
No transformations have been recorded yet.

**What to inspect:** Initialise and print an empty log with named fields. An empty log is the expected output at this stage, not evidence that cleaning has occurred.

## Example 3.28.3 — Remove confirmed exact duplicates

**Website locator:** Example 3.28.3

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

# MAIN DEMONSTRATION
mask = df.duplicated(keep=False)
print("Rows involved in exact duplicates:", int(mask.sum()))
print("Extra copies beyond the first:", int(df.duplicated().sum()))
print(df.loc[mask].to_string(index=False))

Rows involved in exact duplicates: 2
Extra copies beyond the first: 1
  record_id report_month   city service_type  cases_received  cases_resolved resolution_days  satisfaction_score  digital_cases  in_person_cases  repeat_contacts  complaints_received  staff_hours                                                                 feedback
SR2026-0027   2026-02-01 Aarhus    Transport             110             102             4.9                 4.2             79               31                6                    7         42.5 The digital form worked well, although some instructions were confusing.
SR2026-0027   2026-02-01 Aarhus    Transport             110             102             4.9                 4.2             79               31                6                    7         42.5 The digital form worked well, although some instructions were confusing.

**What to inspect:** Reload the original CSV and print the exact-copy candidates before removal. The number of involved rows differs from the number of excess copies.

## Example 3.28.4 — Remove confirmed exact duplicates (continued)

**Website locator:** Example 3.28.4

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []
# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})

# MAIN DEMONSTRATION
print("Raw rows:", len(df_raw))
print("Rows after removing the confirmed exact copy:", len(df))
print(pd.DataFrame(transformation_log).to_string(index=False))

Raw rows: 121
Rows after removing the confirmed exact copy: 120
 step             variable                           action             rationale  rows_affected               reversible                                                notes
    1 all original columns Remove confirmed exact duplicate Avoid double-counting              1 Yes, raw source retained Repeated IDs with different values remain for review

**What to inspect:** Reload the raw file, remove the confirmed duplicate and print both row counts and the recorded decision.

## Example 3.28.5 — Standardise category spacing and capitalisation

**Website locator:** Example 3.28.5

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []
# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})
# Change formatting only. Do not guess whether different labels are equivalent.
for column in ["city", "service_type"]:
    before = df[column].astype("string")
    after = before.str.strip().str.title()
    changed = before.ne(after).fillna(False)
    df[column] = after
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Strip edge spaces and use title case",
        "rationale": "Make formatting variants comparable",
        "rows_affected": int(changed.sum()), "reversible": "Yes, raw source retained",
        "notes": "No undocumented category aliases merged"
    })

# MAIN DEMONSTRATION
print("Raw city labels:", sorted(df_raw["city"].dropna().unique()))
print("Formatted city labels:", sorted(df["city"].dropna().unique()))
print("Formatted services:", sorted(df["service_type"].dropna().unique()))
print(pd.DataFrame(transformation_log)[["variable", "action", "rows_affected"]].to_string(index=False))

Raw city labels: [' copenhagen ', 'AALBORG', 'Aalborg', 'Aarhus', 'Copenhagen', 'Koebenhavn', 'Odense', 'Odense ', 'aarhus']
Formatted city labels: ['Aalborg', 'Aarhus', 'Copenhagen', 'Koebenhavn', 'Odense']
Formatted services: ['Citizen Services', 'Employment', 'Employment Services', 'Housing', 'Transport', 'Waste']
            variable                               action  rows_affected
all original columns     Remove confirmed exact duplicate              1
                city Strip edge spaces and use title case              4
        service_type Strip edge spaces and use title case              3

**What to inspect:** Repeat only the required input and duplicate setup, then print category labels before/after and the measured changes. Distinct labels such as Koebenhavn remain for review.

## Example 3.28.6 — Convert intended numeric columns

**Website locator:** Example 3.28.6

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []
# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})
numeric_columns = [
    "cases_received", "cases_resolved", "resolution_days", "satisfaction_score",
    "digital_cases", "in_person_cases", "repeat_contacts", "complaints_received", "staff_hours"
]
for column in numeric_columns:
    before = df[column].copy()
    converted = pd.to_numeric(before, errors="coerce")
    failed = before.notna() & converted.isna()
    df[column] = converted
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Convert numeric representation",
        "rationale": "Expose unconvertible values and enable numeric checks",
        "rows_affected": int(failed.sum()), "reversible": "Yes, raw source retained",
        "notes": "Count is newly missing values, not all valid numeric conversions"
    })

# MAIN DEMONSTRATION
print("Numeric dtypes:")
print(df[numeric_columns].dtypes.to_string())
print("\nNewly missing values by conversion:")
print(pd.DataFrame(transformation_log).query("action == 'Convert numeric representation'")[["variable", "rows_affected"]].to_string(index=False))

Numeric dtypes:
cases_received           int64
cases_resolved           int64
resolution_days        float64
satisfaction_score     float64
digital_cases            int64
in_person_cases          int64
repeat_contacts          int64
complaints_received      int64
staff_hours            float64

Newly missing values by conversion:
           variable  rows_affected
     cases_received              0
     cases_resolved              0
    resolution_days              3
 satisfaction_score              0
      digital_cases              0
    in_person_cases              0
    repeat_contacts              0
complaints_received              0
        staff_hours              0

**What to inspect:** Rebuild the required inputs, convert each intended numeric field and print dtypes and newly missing counts. Existing missing values are not counted as new conversion failures.

## Example 3.28.7 — Convert the month column

**Website locator:** Example 3.28.7

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []
# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})
before_month = df["report_month"].copy()
df["report_month"] = pd.to_datetime(before_month, format="%Y-%m-%d", errors="coerce")
failed_dates = before_month.notna() & df["report_month"].isna()
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "report_month",
    "action": "Parse YYYY-MM-DD dates", "rationale": "Expose invalid dates without guessing",
    "rows_affected": int(failed_dates.sum()), "reversible": "Yes, raw source retained",
    "notes": "Count is newly missing dates; invalid source values become NaT"
})

# MAIN DEMONSTRATION
print("Newly invalid dates:", int(failed_dates.sum()))
print(df.loc[df["report_month"].isna(), ["record_id", "report_month"]].to_string(index=False))
print("Parsed dtype:", df["report_month"].dtype)

Newly invalid dates: 1
  record_id report_month
SR2026-0044          NaT
Parsed dtype: datetime64[ns]

**What to inspect:** Parse the documented YYYY-MM-DD dates in a fresh copy and show unusable dates and the resulting dtype.

## Example 3.28.8 — Create quality flags

**Website locator:** Example 3.28.8

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})

# Change formatting only. Do not guess whether different labels are equivalent.
for column in ["city", "service_type"]:
    before = df[column].astype("string")
    after = before.str.strip().str.title()
    changed = before.ne(after).fillna(False)
    df[column] = after
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Strip edge spaces and use title case",
        "rationale": "Make formatting variants comparable",
        "rows_affected": int(changed.sum()), "reversible": "Yes, raw source retained",
        "notes": "No undocumented category aliases merged"
    })

numeric_columns = [
    "cases_received", "cases_resolved", "resolution_days", "satisfaction_score",
    "digital_cases", "in_person_cases", "repeat_contacts", "complaints_received", "staff_hours"
]
for column in numeric_columns:
    before = df[column].copy()
    converted = pd.to_numeric(before, errors="coerce")
    failed = before.notna() & converted.isna()
    df[column] = converted
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Convert numeric representation",
        "rationale": "Expose unconvertible values and enable numeric checks",
        "rows_affected": int(failed.sum()), "reversible": "Yes, raw source retained",
        "notes": "Count is newly missing values, not all valid numeric conversions"
    })

before_month = df["report_month"].copy()
df["report_month"] = pd.to_datetime(before_month, format="%Y-%m-%d", errors="coerce")
failed_dates = before_month.notna() & df["report_month"].isna()
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "report_month",
    "action": "Parse YYYY-MM-DD dates", "rationale": "Expose invalid dates without guessing",
    "rows_affected": int(failed_dates.sum()), "reversible": "Yes, raw source retained",
    "notes": "Count is newly missing dates; invalid source values become NaT"
})

# A flag requests review. Keep questionable records in the master table.
df["flag_invalid_month"] = df["report_month"].isna()
df["flag_invalid_satisfaction"] = df["satisfaction_score"].notna() & ~df["satisfaction_score"].between(1, 5)
df["flag_negative_cases_received"] = df["cases_received"] < 0
df["flag_negative_complaints"] = df["complaints_received"] < 0
df["flag_zero_or_negative_staff_hours"] = df["staff_hours"] <= 0
df["flag_resolved_gt_received"] = df["cases_resolved"] > df["cases_received"]
channels_present = df[["cases_received", "digital_cases", "in_person_cases"]].notna().all(axis=1)
df["flag_channel_mismatch"] = channels_present & (
    df["digital_cases"] + df["in_person_cases"] != df["cases_received"]
)
df["flag_repeat_gt_received"] = df["repeat_contacts"] > df["cases_received"]
df["flag_repeated_id"] = df["record_id"].duplicated(keep=False)
known_cities = {"Copenhagen", "Aarhus", "Odense", "Aalborg"}
known_services = {"Housing", "Transport", "Employment", "Waste", "Citizen Services"}
df["flag_unrecognised_city"] = df["city"].notna() & ~df["city"].isin(known_cities)
df["flag_unrecognised_service"] = df["service_type"].notna() & ~df["service_type"].isin(known_services)
df["flag_missing_feedback"] = df["feedback"].fillna("").str.strip().eq("")
flag_columns = [column for column in df.columns if column.startswith("flag_")]
df["flag_any_quality_issue"] = df[flag_columns].any(axis=1)
for column in flag_columns:
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Flag and retain", "rationale": "Make unresolved issues visible",
        "rows_affected": int(df[column].sum()), "reversible": "Yes, no record removed",
        "notes": "Counts may overlap; False does not establish complete validity"
    })

# MAIN DEMONSTRATION
quality_summary = df[flag_columns].sum().sort_values(ascending=False)
print("INDIVIDUAL REVIEW FLAGS")
print(quality_summary.to_string())
print("Rows with one or more flags:", int(df["flag_any_quality_issue"].sum()))
print("Missing numeric values are audited separately:")
print(df[numeric_columns].isna().sum().to_string())

INDIVIDUAL REVIEW FLAGS
flag_resolved_gt_received            3
flag_missing_feedback                3
flag_invalid_satisfaction            2
flag_channel_mismatch                2
flag_repeat_gt_received              2
flag_repeated_id                     2
flag_invalid_month                   1
flag_negative_cases_received         1
flag_negative_complaints             1
flag_zero_or_negative_staff_hours    1
flag_unrecognised_city               1
flag_unrecognised_service            1
Rows with one or more flags: 17
Missing numeric values are audited separately:
cases_received         0
cases_resolved         0
resolution_days        3
satisfaction_score     4
digital_cases          0
in_person_cases        0
repeat_contacts        0
complaints_received    0
staff_hours            0

**What to inspect:** Rebuild the structural cleaning and flags in this block. Print individual flag counts and the number of uniquely flagged rows. Flags can overlap; missing numeric values still need separate inspection.

## Example 3.28.9 — Create one combined flag

**Website locator:** Example 3.28.9

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})

# Change formatting only. Do not guess whether different labels are equivalent.
for column in ["city", "service_type"]:
    before = df[column].astype("string")
    after = before.str.strip().str.title()
    changed = before.ne(after).fillna(False)
    df[column] = after
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Strip edge spaces and use title case",
        "rationale": "Make formatting variants comparable",
        "rows_affected": int(changed.sum()), "reversible": "Yes, raw source retained",
        "notes": "No undocumented category aliases merged"
    })

numeric_columns = [
    "cases_received", "cases_resolved", "resolution_days", "satisfaction_score",
    "digital_cases", "in_person_cases", "repeat_contacts", "complaints_received", "staff_hours"
]
for column in numeric_columns:
    before = df[column].copy()
    converted = pd.to_numeric(before, errors="coerce")
    failed = before.notna() & converted.isna()
    df[column] = converted
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Convert numeric representation",
        "rationale": "Expose unconvertible values and enable numeric checks",
        "rows_affected": int(failed.sum()), "reversible": "Yes, raw source retained",
        "notes": "Count is newly missing values, not all valid numeric conversions"
    })

before_month = df["report_month"].copy()
df["report_month"] = pd.to_datetime(before_month, format="%Y-%m-%d", errors="coerce")
failed_dates = before_month.notna() & df["report_month"].isna()
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "report_month",
    "action": "Parse YYYY-MM-DD dates", "rationale": "Expose invalid dates without guessing",
    "rows_affected": int(failed_dates.sum()), "reversible": "Yes, raw source retained",
    "notes": "Count is newly missing dates; invalid source values become NaT"
})

# A flag requests review. Keep questionable records in the master table.
df["flag_invalid_month"] = df["report_month"].isna()
df["flag_invalid_satisfaction"] = df["satisfaction_score"].notna() & ~df["satisfaction_score"].between(1, 5)
df["flag_negative_cases_received"] = df["cases_received"] < 0
df["flag_negative_complaints"] = df["complaints_received"] < 0
df["flag_zero_or_negative_staff_hours"] = df["staff_hours"] <= 0
df["flag_resolved_gt_received"] = df["cases_resolved"] > df["cases_received"]
channels_present = df[["cases_received", "digital_cases", "in_person_cases"]].notna().all(axis=1)
df["flag_channel_mismatch"] = channels_present & (
    df["digital_cases"] + df["in_person_cases"] != df["cases_received"]
)
df["flag_repeat_gt_received"] = df["repeat_contacts"] > df["cases_received"]
df["flag_repeated_id"] = df["record_id"].duplicated(keep=False)
known_cities = {"Copenhagen", "Aarhus", "Odense", "Aalborg"}
known_services = {"Housing", "Transport", "Employment", "Waste", "Citizen Services"}
df["flag_unrecognised_city"] = df["city"].notna() & ~df["city"].isin(known_cities)
df["flag_unrecognised_service"] = df["service_type"].notna() & ~df["service_type"].isin(known_services)
df["flag_missing_feedback"] = df["feedback"].fillna("").str.strip().eq("")
flag_columns = [column for column in df.columns if column.startswith("flag_")]
df["flag_any_quality_issue"] = df[flag_columns].any(axis=1)
for column in flag_columns:
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Flag and retain", "rationale": "Make unresolved issues visible",
        "rows_affected": int(df[column].sum()), "reversible": "Yes, no record removed",
        "notes": "Counts may overlap; False does not establish complete validity"
    })

# MAIN DEMONSTRATION
quality_summary = df[flag_columns].sum().sort_values(ascending=False)
print("INDIVIDUAL REVIEW FLAGS")
print(quality_summary.to_string())
print("Rows with one or more flags:", int(df["flag_any_quality_issue"].sum()))
print("Missing numeric values are audited separately:")
print(df[numeric_columns].isna().sum().to_string())

INDIVIDUAL REVIEW FLAGS
flag_resolved_gt_received            3
flag_missing_feedback                3
flag_invalid_satisfaction            2
flag_channel_mismatch                2
flag_repeat_gt_received              2
flag_repeated_id                     2
flag_invalid_month                   1
flag_negative_cases_received         1
flag_negative_complaints             1
flag_zero_or_negative_staff_hours    1
flag_unrecognised_city               1
flag_unrecognised_service            1
Rows with one or more flags: 17
Missing numeric values are audited separately:
cases_received         0
cases_resolved         0
resolution_days        3
satisfaction_score     4
digital_cases          0
in_person_cases        0
repeat_contacts        0
complaints_received    0
staff_hours            0

**What to inspect:** Rebuild the structural cleaning and flags in this block. Print individual flag counts and the number of uniquely flagged rows. Flags can overlap; missing numeric values still need separate inspection.

## Example 3.28.10 — Prepare text

**Website locator:** Example 3.28.10

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []
# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})
import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
# The original feedback stays unchanged; missingness has a separate flag.
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))
feedback_present = df["feedback"].notna() & df["feedback"].fillna("").str.strip().ne("")
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "feedback",
    "action": "Derive tokens and prepared text", "rationale": "Prepare a separate representation for counting",
    "rows_affected": int(feedback_present.sum()), "reversible": "Yes, original feedback retained",
    "notes": "Count is non-empty source feedback; empty token lists do not imply neutral sentiment"
})

# MAIN DEMONSTRATION
print(df[["record_id", "feedback", "feedback_tokens", "feedback_clean"]].head(8).to_string(index=False))
print("Raw feedback missing:", int(df["feedback"].isna().sum()))
print("Negation check:", prepare_feedback("The wait was not long."))

  record_id                                                                          feedback                                                                    feedback_tokens                                                          feedback_clean
SR2026-0001   The guidance was clear, but the supporting-document requirements caused delays.                                    [guidance, clear, requirements, caused, delays]                               guidance clear requirements caused delays
SR2026-0002                Several users asked for clearer information about service changes.                    [several, users, asked, clearer, information, service, changes]                 several users asked clearer information service changes
SR2026-0003                                 Useful advice and a friendly response from staff.                                        [useful, advice, friendly, response, staff]                                   useful advice friendly response staff
SR2026-0004                      Helpful guidance, but some users reported delayed follow-up.                                      [helpful, guidance, users, reported, delayed]                                 helpful guidance users reported delayed
SR2026-0005                             The response was fast and the information was useful.                                              [response, fast, information, useful]                                        response fast information useful
SR2026-0006 Helpful staff explained the housing process, although the waiting time felt long. [helpful, staff, explained, housing, process, although, waiting, time, felt, long] helpful staff explained housing process although waiting time felt long
SR2026-0007                Several users asked for clearer information about service changes.                    [several, users, asked, clearer, information, service, changes]                 several users asked clearer information service changes
SR2026-0008        The answer was useful, although the waiting time was longer than expected.                        [answer, useful, although, waiting, time, longer, expected]                     answer useful although waiting time longer expected
Raw feedback missing: 3
Negation check: ['wait', 'not', 'long']

**What to inspect:** Load a fresh working copy and include the complete NLTK setup and function. Print a text comparison and a negation check; preserve the raw feedback.

## Example 3.28.11 — Compare raw and cleaned structure

**Website locator:** Example 3.28.11

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})

# Change formatting only. Do not guess whether different labels are equivalent.
for column in ["city", "service_type"]:
    before = df[column].astype("string")
    after = before.str.strip().str.title()
    changed = before.ne(after).fillna(False)
    df[column] = after
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Strip edge spaces and use title case",
        "rationale": "Make formatting variants comparable",
        "rows_affected": int(changed.sum()), "reversible": "Yes, raw source retained",
        "notes": "No undocumented category aliases merged"
    })

numeric_columns = [
    "cases_received", "cases_resolved", "resolution_days", "satisfaction_score",
    "digital_cases", "in_person_cases", "repeat_contacts", "complaints_received", "staff_hours"
]
for column in numeric_columns:
    before = df[column].copy()
    converted = pd.to_numeric(before, errors="coerce")
    failed = before.notna() & converted.isna()
    df[column] = converted
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Convert numeric representation",
        "rationale": "Expose unconvertible values and enable numeric checks",
        "rows_affected": int(failed.sum()), "reversible": "Yes, raw source retained",
        "notes": "Count is newly missing values, not all valid numeric conversions"
    })

before_month = df["report_month"].copy()
df["report_month"] = pd.to_datetime(before_month, format="%Y-%m-%d", errors="coerce")
failed_dates = before_month.notna() & df["report_month"].isna()
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "report_month",
    "action": "Parse YYYY-MM-DD dates", "rationale": "Expose invalid dates without guessing",
    "rows_affected": int(failed_dates.sum()), "reversible": "Yes, raw source retained",
    "notes": "Count is newly missing dates; invalid source values become NaT"
})

# A flag requests review. Keep questionable records in the master table.
df["flag_invalid_month"] = df["report_month"].isna()
df["flag_invalid_satisfaction"] = df["satisfaction_score"].notna() & ~df["satisfaction_score"].between(1, 5)
df["flag_negative_cases_received"] = df["cases_received"] < 0
df["flag_negative_complaints"] = df["complaints_received"] < 0
df["flag_zero_or_negative_staff_hours"] = df["staff_hours"] <= 0
df["flag_resolved_gt_received"] = df["cases_resolved"] > df["cases_received"]
channels_present = df[["cases_received", "digital_cases", "in_person_cases"]].notna().all(axis=1)
df["flag_channel_mismatch"] = channels_present & (
    df["digital_cases"] + df["in_person_cases"] != df["cases_received"]
)
df["flag_repeat_gt_received"] = df["repeat_contacts"] > df["cases_received"]
df["flag_repeated_id"] = df["record_id"].duplicated(keep=False)
known_cities = {"Copenhagen", "Aarhus", "Odense", "Aalborg"}
known_services = {"Housing", "Transport", "Employment", "Waste", "Citizen Services"}
df["flag_unrecognised_city"] = df["city"].notna() & ~df["city"].isin(known_cities)
df["flag_unrecognised_service"] = df["service_type"].notna() & ~df["service_type"].isin(known_services)
df["flag_missing_feedback"] = df["feedback"].fillna("").str.strip().eq("")
flag_columns = [column for column in df.columns if column.startswith("flag_")]
df["flag_any_quality_issue"] = df[flag_columns].any(axis=1)
for column in flag_columns:
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Flag and retain", "rationale": "Make unresolved issues visible",
        "rows_affected": int(df[column].sum()), "reversible": "Yes, no record removed",
        "notes": "Counts may overlap; False does not establish complete validity"
    })

import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
# The original feedback stays unchanged; missingness has a separate flag.
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))
feedback_present = df["feedback"].notna() & df["feedback"].fillna("").str.strip().ne("")
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "feedback",
    "action": "Derive tokens and prepared text", "rationale": "Prepare a separate representation for counting",
    "rows_affected": int(feedback_present.sum()), "reversible": "Yes, original feedback retained",
    "notes": "Count is non-empty source feedback; empty token lists do not imply neutral sentiment"
})

log_df = pd.DataFrame(transformation_log)

# MAIN DEMONSTRATION
print("Raw shape:", df_raw.shape)
print("Prepared master shape:", df.shape)
print("Raw city labels:", sorted(df_raw["city"].dropna().unique()))
print("Prepared city labels:", sorted(df["city"].dropna().unique()))
print("Raw feedback preserved:", df["feedback"].equals(df_raw.loc[df.index, "feedback"]))

Raw shape: (121, 14)
Prepared master shape: (120, 29)
Raw city labels: [' copenhagen ', 'AALBORG', 'Aalborg', 'Aarhus', 'Copenhagen', 'Koebenhavn', 'Odense', 'Odense ', 'aarhus']
Prepared city labels: ['Aalborg', 'Aarhus', 'Copenhagen', 'Koebenhavn', 'Odense']
Raw feedback preserved: True

**What to inspect:** Run the complete transparent workflow inside this block before comparing raw and prepared structures. Extra columns document derived text and retained quality flags.

## Example 3.28.12 — Summarise quality flags

**Website locator:** Example 3.28.12

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})

# Change formatting only. Do not guess whether different labels are equivalent.
for column in ["city", "service_type"]:
    before = df[column].astype("string")
    after = before.str.strip().str.title()
    changed = before.ne(after).fillna(False)
    df[column] = after
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Strip edge spaces and use title case",
        "rationale": "Make formatting variants comparable",
        "rows_affected": int(changed.sum()), "reversible": "Yes, raw source retained",
        "notes": "No undocumented category aliases merged"
    })

numeric_columns = [
    "cases_received", "cases_resolved", "resolution_days", "satisfaction_score",
    "digital_cases", "in_person_cases", "repeat_contacts", "complaints_received", "staff_hours"
]
for column in numeric_columns:
    before = df[column].copy()
    converted = pd.to_numeric(before, errors="coerce")
    failed = before.notna() & converted.isna()
    df[column] = converted
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Convert numeric representation",
        "rationale": "Expose unconvertible values and enable numeric checks",
        "rows_affected": int(failed.sum()), "reversible": "Yes, raw source retained",
        "notes": "Count is newly missing values, not all valid numeric conversions"
    })

before_month = df["report_month"].copy()
df["report_month"] = pd.to_datetime(before_month, format="%Y-%m-%d", errors="coerce")
failed_dates = before_month.notna() & df["report_month"].isna()
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "report_month",
    "action": "Parse YYYY-MM-DD dates", "rationale": "Expose invalid dates without guessing",
    "rows_affected": int(failed_dates.sum()), "reversible": "Yes, raw source retained",
    "notes": "Count is newly missing dates; invalid source values become NaT"
})

# A flag requests review. Keep questionable records in the master table.
df["flag_invalid_month"] = df["report_month"].isna()
df["flag_invalid_satisfaction"] = df["satisfaction_score"].notna() & ~df["satisfaction_score"].between(1, 5)
df["flag_negative_cases_received"] = df["cases_received"] < 0
df["flag_negative_complaints"] = df["complaints_received"] < 0
df["flag_zero_or_negative_staff_hours"] = df["staff_hours"] <= 0
df["flag_resolved_gt_received"] = df["cases_resolved"] > df["cases_received"]
channels_present = df[["cases_received", "digital_cases", "in_person_cases"]].notna().all(axis=1)
df["flag_channel_mismatch"] = channels_present & (
    df["digital_cases"] + df["in_person_cases"] != df["cases_received"]
)
df["flag_repeat_gt_received"] = df["repeat_contacts"] > df["cases_received"]
df["flag_repeated_id"] = df["record_id"].duplicated(keep=False)
known_cities = {"Copenhagen", "Aarhus", "Odense", "Aalborg"}
known_services = {"Housing", "Transport", "Employment", "Waste", "Citizen Services"}
df["flag_unrecognised_city"] = df["city"].notna() & ~df["city"].isin(known_cities)
df["flag_unrecognised_service"] = df["service_type"].notna() & ~df["service_type"].isin(known_services)
df["flag_missing_feedback"] = df["feedback"].fillna("").str.strip().eq("")
flag_columns = [column for column in df.columns if column.startswith("flag_")]
df["flag_any_quality_issue"] = df[flag_columns].any(axis=1)
for column in flag_columns:
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Flag and retain", "rationale": "Make unresolved issues visible",
        "rows_affected": int(df[column].sum()), "reversible": "Yes, no record removed",
        "notes": "Counts may overlap; False does not establish complete validity"
    })

# MAIN DEMONSTRATION
quality_summary = df[flag_columns].sum().sort_values(ascending=False)
print("INDIVIDUAL REVIEW FLAGS")
print(quality_summary.to_string())
print("Rows with one or more flags:", int(df["flag_any_quality_issue"].sum()))
print("Missing numeric values are audited separately:")
print(df[numeric_columns].isna().sum().to_string())

INDIVIDUAL REVIEW FLAGS
flag_resolved_gt_received            3
flag_missing_feedback                3
flag_invalid_satisfaction            2
flag_channel_mismatch                2
flag_repeat_gt_received              2
flag_repeated_id                     2
flag_invalid_month                   1
flag_negative_cases_received         1
flag_negative_complaints             1
flag_zero_or_negative_staff_hours    1
flag_unrecognised_city               1
flag_unrecognised_service            1
Rows with one or more flags: 17
Missing numeric values are audited separately:
cases_received         0
cases_resolved         0
resolution_days        3
satisfaction_score     4
digital_cases          0
in_person_cases        0
repeat_contacts        0
complaints_received    0
staff_hours            0

**What to inspect:** Rebuild the structural cleaning and flags in this block. Print individual flag counts and the number of uniquely flagged rows. Flags can overlap; missing numeric values still need separate inspection.

## Example 3.28.13 — Create the final transformation-log DataFrame

**Website locator:** Example 3.28.13

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})

# Change formatting only. Do not guess whether different labels are equivalent.
for column in ["city", "service_type"]:
    before = df[column].astype("string")
    after = before.str.strip().str.title()
    changed = before.ne(after).fillna(False)
    df[column] = after
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Strip edge spaces and use title case",
        "rationale": "Make formatting variants comparable",
        "rows_affected": int(changed.sum()), "reversible": "Yes, raw source retained",
        "notes": "No undocumented category aliases merged"
    })

numeric_columns = [
    "cases_received", "cases_resolved", "resolution_days", "satisfaction_score",
    "digital_cases", "in_person_cases", "repeat_contacts", "complaints_received", "staff_hours"
]
for column in numeric_columns:
    before = df[column].copy()
    converted = pd.to_numeric(before, errors="coerce")
    failed = before.notna() & converted.isna()
    df[column] = converted
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Convert numeric representation",
        "rationale": "Expose unconvertible values and enable numeric checks",
        "rows_affected": int(failed.sum()), "reversible": "Yes, raw source retained",
        "notes": "Count is newly missing values, not all valid numeric conversions"
    })

before_month = df["report_month"].copy()
df["report_month"] = pd.to_datetime(before_month, format="%Y-%m-%d", errors="coerce")
failed_dates = before_month.notna() & df["report_month"].isna()
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "report_month",
    "action": "Parse YYYY-MM-DD dates", "rationale": "Expose invalid dates without guessing",
    "rows_affected": int(failed_dates.sum()), "reversible": "Yes, raw source retained",
    "notes": "Count is newly missing dates; invalid source values become NaT"
})

# A flag requests review. Keep questionable records in the master table.
df["flag_invalid_month"] = df["report_month"].isna()
df["flag_invalid_satisfaction"] = df["satisfaction_score"].notna() & ~df["satisfaction_score"].between(1, 5)
df["flag_negative_cases_received"] = df["cases_received"] < 0
df["flag_negative_complaints"] = df["complaints_received"] < 0
df["flag_zero_or_negative_staff_hours"] = df["staff_hours"] <= 0
df["flag_resolved_gt_received"] = df["cases_resolved"] > df["cases_received"]
channels_present = df[["cases_received", "digital_cases", "in_person_cases"]].notna().all(axis=1)
df["flag_channel_mismatch"] = channels_present & (
    df["digital_cases"] + df["in_person_cases"] != df["cases_received"]
)
df["flag_repeat_gt_received"] = df["repeat_contacts"] > df["cases_received"]
df["flag_repeated_id"] = df["record_id"].duplicated(keep=False)
known_cities = {"Copenhagen", "Aarhus", "Odense", "Aalborg"}
known_services = {"Housing", "Transport", "Employment", "Waste", "Citizen Services"}
df["flag_unrecognised_city"] = df["city"].notna() & ~df["city"].isin(known_cities)
df["flag_unrecognised_service"] = df["service_type"].notna() & ~df["service_type"].isin(known_services)
df["flag_missing_feedback"] = df["feedback"].fillna("").str.strip().eq("")
flag_columns = [column for column in df.columns if column.startswith("flag_")]
df["flag_any_quality_issue"] = df[flag_columns].any(axis=1)
for column in flag_columns:
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Flag and retain", "rationale": "Make unresolved issues visible",
        "rows_affected": int(df[column].sum()), "reversible": "Yes, no record removed",
        "notes": "Counts may overlap; False does not establish complete validity"
    })

import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
# The original feedback stays unchanged; missingness has a separate flag.
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))
feedback_present = df["feedback"].notna() & df["feedback"].fillna("").str.strip().ne("")
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "feedback",
    "action": "Derive tokens and prepared text", "rationale": "Prepare a separate representation for counting",
    "rows_affected": int(feedback_present.sum()), "reversible": "Yes, original feedback retained",
    "notes": "Count is non-empty source feedback; empty token lists do not imply neutral sentiment"
})

log_df = pd.DataFrame(transformation_log)

# MAIN DEMONSTRATION
print("Transformation-log entries:", len(log_df))
print(log_df[["step", "variable", "action", "rows_affected"]].to_string(index=False))
print("Each entry also retains rationale, reversibility and notes.")

Transformation-log entries: 26
 step                          variable                               action  rows_affected
    1              all original columns     Remove confirmed exact duplicate              1
    2                              city Strip edge spaces and use title case              4
    3                      service_type Strip edge spaces and use title case              3
    4                    cases_received       Convert numeric representation              0
    5                    cases_resolved       Convert numeric representation              0
    6                   resolution_days       Convert numeric representation              3
    7                satisfaction_score       Convert numeric representation              0
    8                     digital_cases       Convert numeric representation              0
    9                   in_person_cases       Convert numeric representation              0
   10                   repeat_contacts       Convert numeric representation              0
   11               complaints_received       Convert numeric representation              0
   12                       staff_hours       Convert numeric representation              0
   13                      report_month               Parse YYYY-MM-DD dates              1
   14                flag_invalid_month                      Flag and retain              1
   15         flag_invalid_satisfaction                      Flag and retain              2
   16      flag_negative_cases_received                      Flag and retain              1
   17          flag_negative_complaints                      Flag and retain              1
   18 flag_zero_or_negative_staff_hours                      Flag and retain              1
   19         flag_resolved_gt_received                      Flag and retain              3
   20             flag_channel_mismatch                      Flag and retain              2
   21           flag_repeat_gt_received                      Flag and retain              2
   22                  flag_repeated_id                      Flag and retain              2
   23            flag_unrecognised_city                      Flag and retain              1
   24         flag_unrecognised_service                      Flag and retain              1
   25             flag_missing_feedback                      Flag and retain              3
   26                          feedback      Derive tokens and prepared text            117
Each entry also retains rationale, reversibility and notes.

**What to inspect:** Rebuild the full workflow and display the log calculated from those actual operations. Counts have explicit meanings, and overlapping flag counts must not be added as unique records.

## Example 3.28.14 — Save outputs using new filenames

**Website locator:** Example 3.28.14

**Run independently:** Use the complete code cell for this item. It recreates its inputs and prints the result; earlier cells are not required. First-time NLTK resource downloads and CSV loading need internet.

In [1]:
# Run this complete block on its own; no earlier cell is required.
import pandas as pd  # Work with tables and missing values.
# Read the canonical synthetic data. Every run starts from this source.
RAW_URL = "https://raw.githubusercontent.com/asmrabbi/E26_TAN7_Scripting_CPH/main/data/E26_TAN7_service_experience_raw.csv"
df_raw = pd.read_csv(RAW_URL)
df = df_raw.copy(deep=True)  # Preserve an unchanged source table.
transformation_log = []

# This teaching file contains a confirmed exact copy of one observation.
rows_before = len(df)
df = df.drop_duplicates().copy()
rows_removed = rows_before - len(df)
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "all original columns",
    "action": "Remove confirmed exact duplicate", "rationale": "Avoid double-counting",
    "rows_affected": int(rows_removed), "reversible": "Yes, raw source retained",
    "notes": "Repeated IDs with different values remain for review"
})

# Change formatting only. Do not guess whether different labels are equivalent.
for column in ["city", "service_type"]:
    before = df[column].astype("string")
    after = before.str.strip().str.title()
    changed = before.ne(after).fillna(False)
    df[column] = after
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Strip edge spaces and use title case",
        "rationale": "Make formatting variants comparable",
        "rows_affected": int(changed.sum()), "reversible": "Yes, raw source retained",
        "notes": "No undocumented category aliases merged"
    })

numeric_columns = [
    "cases_received", "cases_resolved", "resolution_days", "satisfaction_score",
    "digital_cases", "in_person_cases", "repeat_contacts", "complaints_received", "staff_hours"
]
for column in numeric_columns:
    before = df[column].copy()
    converted = pd.to_numeric(before, errors="coerce")
    failed = before.notna() & converted.isna()
    df[column] = converted
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Convert numeric representation",
        "rationale": "Expose unconvertible values and enable numeric checks",
        "rows_affected": int(failed.sum()), "reversible": "Yes, raw source retained",
        "notes": "Count is newly missing values, not all valid numeric conversions"
    })

before_month = df["report_month"].copy()
df["report_month"] = pd.to_datetime(before_month, format="%Y-%m-%d", errors="coerce")
failed_dates = before_month.notna() & df["report_month"].isna()
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "report_month",
    "action": "Parse YYYY-MM-DD dates", "rationale": "Expose invalid dates without guessing",
    "rows_affected": int(failed_dates.sum()), "reversible": "Yes, raw source retained",
    "notes": "Count is newly missing dates; invalid source values become NaT"
})

# A flag requests review. Keep questionable records in the master table.
df["flag_invalid_month"] = df["report_month"].isna()
df["flag_invalid_satisfaction"] = df["satisfaction_score"].notna() & ~df["satisfaction_score"].between(1, 5)
df["flag_negative_cases_received"] = df["cases_received"] < 0
df["flag_negative_complaints"] = df["complaints_received"] < 0
df["flag_zero_or_negative_staff_hours"] = df["staff_hours"] <= 0
df["flag_resolved_gt_received"] = df["cases_resolved"] > df["cases_received"]
channels_present = df[["cases_received", "digital_cases", "in_person_cases"]].notna().all(axis=1)
df["flag_channel_mismatch"] = channels_present & (
    df["digital_cases"] + df["in_person_cases"] != df["cases_received"]
)
df["flag_repeat_gt_received"] = df["repeat_contacts"] > df["cases_received"]
df["flag_repeated_id"] = df["record_id"].duplicated(keep=False)
known_cities = {"Copenhagen", "Aarhus", "Odense", "Aalborg"}
known_services = {"Housing", "Transport", "Employment", "Waste", "Citizen Services"}
df["flag_unrecognised_city"] = df["city"].notna() & ~df["city"].isin(known_cities)
df["flag_unrecognised_service"] = df["service_type"].notna() & ~df["service_type"].isin(known_services)
df["flag_missing_feedback"] = df["feedback"].fillna("").str.strip().eq("")
flag_columns = [column for column in df.columns if column.startswith("flag_")]
df["flag_any_quality_issue"] = df[flag_columns].any(axis=1)
for column in flag_columns:
    transformation_log.append({
        "step": len(transformation_log) + 1, "variable": column,
        "action": "Flag and retain", "rationale": "Make unresolved issues visible",
        "rows_affected": int(df[column].sum()), "reversible": "Yes, no record removed",
        "notes": "Counts may overlap; False does not establish complete validity"
    })

import pandas as pd  # Work with tables and missing values.
import nltk  # Tokenisation and English stop-word tools.
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# A fresh runtime needs these resources. Existing downloads are reused.
resources = [('punkt', 'tokenizers/punkt'), ('punkt_tab', 'tokenizers/punkt_tab'), ('stopwords', 'corpora/stopwords')]
for name, resource_path in resources:
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(name, quiet=True, raise_on_error=True)
# Preserve these negation words because removing them can reverse meaning.
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

def prepare_feedback(text):
    if pd.isna(text):
        return []
    tokens = word_tokenize(str(text).lower())
    return [token for token in tokens
            if token.isalpha() and token not in stop_words]
# The original feedback stays unchanged; missingness has a separate flag.
df["feedback_tokens"] = df["feedback"].apply(prepare_feedback)
df["feedback_clean"] = df["feedback_tokens"].apply(lambda tokens: " ".join(tokens))
feedback_present = df["feedback"].notna() & df["feedback"].fillna("").str.strip().ne("")
transformation_log.append({
    "step": len(transformation_log) + 1, "variable": "feedback",
    "action": "Derive tokens and prepared text", "rationale": "Prepare a separate representation for counting",
    "rows_affected": int(feedback_present.sum()), "reversible": "Yes, original feedback retained",
    "notes": "Count is non-empty source feedback; empty token lists do not imply neutral sentiment"
})

log_df = pd.DataFrame(transformation_log)

# MAIN DEMONSTRATION
from pathlib import Path
# Save student copies in this runtime only. No repository data is overwritten.
output_dir = Path.cwd() / "tutorial_outputs"
output_dir.mkdir(parents=True, exist_ok=True)
clean_file = output_dir / "L06_student_cleaned_copy.csv"
log_file = output_dir / "L06_student_transformation_log.csv"
df.to_csv(clean_file, index=False)
log_df.to_csv(log_file, index=False)
print("Cleaned student copy:", clean_file)
print("Transformation log copy:", log_file)
print("Rows read back from saved copy:", len(pd.read_csv(clean_file)))
print("Log entries read back:", len(pd.read_csv(log_file)))

Cleaned student copy: /Users/asmrabbi/.codex/.chatgpt-projects/g-p-6a5e50d317688191b75203fd88ab7655/tutorial_3_26_29_update/validation/3.28.14/tutorial_outputs/L06_student_cleaned_copy.csv
Transformation log copy: /Users/asmrabbi/.codex/.chatgpt-projects/g-p-6a5e50d317688191b75203fd88ab7655/tutorial_3_26_29_update/validation/3.28.14/tutorial_outputs/L06_student_transformation_log.csv
Rows read back from saved copy: 120
Log entries read back: 26

**What to inspect:** Rebuild the full workflow, save only new student copies inside tutorial_outputs and read them back to print row and log-entry counts. The raw repository file stays unchanged.